Migrate the core of bespin to boto3
delfick/bespin pull request #22
Opened 2017-04-11 01:31 UTC by atward

Migrate `bespin.amazon.credentials` and `bespin.amazon.cloudformation` to use boto3 (#17). This migrates what I consider the core of bespin (environments & stacks).

Untouched modules (`bespin.amazon.ec2`, `s3`, `sqs`, `kms`) will continue to operate using the boto authenticator off either the user's environment, or the overlaid `assume_role` environment.
The migration of the remaining modules will done in separate PRs and will be tracked in #17.

2017-04-11 01:54 UTC, delfick commented
cool, thnx, I'll have a proper look a bit later on :)

2017-04-12 05:35 UTC, atward commented
@delfick could you sign off on this. There's a number of other PRs hanging off it.

2017-04-12 05:38 UTC, delfick commented
ah yes, I'll look now

2017-04-12 05:44 UTC, delfick requested changes
Looks good to me other than the asserts

2017-04-12 05:44 UTC, delfick commented on bespin/amazon/cloudformation.py
> +        assert self.session.region_name == self.region
I'm not a fan of asserts in code.

I'd rather we make session a memoized property than allow it to be passed in

    @hp.memoized_property
    def session(self):
        return boto3.session.Session(region_name=self.region)

2017-04-12 05:44 UTC, delfick commented on bespin/amazon/credentials.py
> +        assert self.session is not None and self.session.region_name == self.region
this should raise BespinError instead of an AssertionError

2017-04-12 05:46 UTC, atward commented on bespin/amazon/cloudformation.py
> +        assert self.session.region_name == self.region
Problem with your example is that is makes a new session for each (CF, EC2, S3...), rather than share the same session.

2017-04-12 05:56 UTC, atward commented on bespin/amazon/cloudformation.py
> +        assert self.session.region_name == self.region
It's not a major objection. Pushed new changes.

2017-04-12 05:56 UTC, atward commented on bespin/amazon/credentials.py
> +        assert self.session is not None and self.session.region_name == self.region
This is more I did something wrong, so changed to ProgrammerError

2017-04-12 06:02 UTC, delfick commented on bespin/amazon/cloudformation.py
> +        assert self.session.region_name == self.region
aaahhh, it is too. I see the difference... hmmmm

Perhaps an object that holds onto a session per region, and we pass that into the intializer, which gets used to generate/reuse a session for that region.....

2017-04-12 06:02 UTC, delfick commented
lgtm

2017-04-12 06:03 UTC, delfick approved these changes

2017-04-12 06:04 UTC, merged